### ISSUE TITLE
I come from China, can you write a detailed deployment tutorial?

### ISSUE THREAD

**Issue by szsyzx** [yuyu1815/twikit_discord_bot#1]
I come from China, can you write a detailed deployment tutorial?

**Comment by yuyu1815** [comment]
I understand.
We're in the middle of production, so we'll need a little time.
I will contact you within a week when it's done.

**Comment by szsyzx** [comment]
Thank you very much. Looking forward to your prompt completion




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月22日(星期二) 上午8:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yuyu1815/twikit_discord_bot] I come from China, can you write a detailed deployment tutorial? (Issue #1)















我明白。
我们正在制作中，所以需要一点时间。
完成后，我会在一周内与你联系。

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
***@***.*** &gt;

**Comment by yuyu1815** [comment]
Thank you for waiting
I am pleased to report that the document is now complete!
